# Generated by Django 5.0.6 on 2025-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
