# Generated by Django 5.0.6 on 2025-11-05 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estimate_estimate_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimateparty',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='会社電話番号'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='customer_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customerclass'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='first_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_estimate_parties', to='core.shop'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gender'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='kana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='カナ'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='last_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_estimate_parties', to='core.shop'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='携帯電話'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimateparty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estimateparty',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='estimateparty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='estimateparty',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='estimateparty',
            name='source_customer',
            field=models.ForeignKey(blank=True, help_text='元となった顧客がある場合のみ参照', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AlterModelTable(
            name='estimateparty',
            table='estimate_parties',
        ),
    ]
