# Generated by Django 5.0.6 on 2025-11-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_alter_estimateparty_options_estimateparty_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trade_in', models.BooleanField(default=False, help_text='Trueなら下取り車両、Falseなら商談車両')),
                ('vehicle_name', models.CharField(blank=True, max_length=100)),
                ('displacement', models.IntegerField(blank=True, null=True)),
                ('model_year', models.CharField(blank=True, max_length=10)),
                ('new_car_type', models.CharField(blank=True, max_length=20)),
                ('color_name', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('model_code', models.CharField(blank=True, max_length=50)),
                ('chassis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_vehicles', to='core.estimate')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
            ],
            options={
                'db_table': 'estimate_vehicles',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('現金', '現金'), ('クレジット', 'クレジット'), ('請求書', '請求書')], max_length=50)),
                ('payment_detail', models.CharField(blank=True, max_length=100)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('credit_company', models.CharField(blank=True, max_length=100)),
                ('credit_first_payment', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('credit_second_payment', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('credit_bonus_payment', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('credit_installments', models.IntegerField(blank=True, null=True)),
                ('credit_start_month', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '支払い情報',
                'verbose_name_plural': '支払い情報',
                'db_table': 'payments',
            },
        ),
    ]
