# Generated by Django 5.0.6 on 2025-11-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estimatevehicle_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_detail',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='現金', max_length=20),
        ),
    ]
