# Generated by Django 5.0.6 on 2025-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_vehicle_bicycle_type_remove_vehicle_key_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registration_locations',
                'ordering': ['id'],
            },
        ),
    ]
