# Generated by Django 5.0.6 on 2025-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_payment_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
