# Generated by Django 5.0.6 on 2025-11-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estimate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_start_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
