# Generated by Django 5.0.6 on 2025-10-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registrationlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='type',
            field=models.CharField(blank=True, choices=[('mandatory', 'Mandatory'), ('optional', 'Optional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclememo',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclewarranty',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclewarranty',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
