# Generated by Django 5.0.6 on 2025-11-12 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_payment_credit_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estimateparty'),
        ),
    ]
