# Generated by Django 5.0.6 on 2025-10-07 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vehicleinsurance_type_alter_vehiclememo_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('disk', models.CharField(default='public', max_length=30)),
                ('mime', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.vehicle')),
            ],
            options={
                'db_table': 'vehicle_images',
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_ima_vehicle_210923_idx')],
            },
        ),
    ]
