# Generated by Django 5.0.6 on 2025-10-07 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vehicleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclememo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='vehiclememo',
            new_name='vehicle_mem_vehicle_8c2a57_idx',
            old_name='core_vehicl_vehicle_25de23_idx',
        ),
        migrations.AlterField(
            model_name='vehiclememo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_memos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='vehiclememo',
            table='vehicle_memos',
        ),
    ]
