# Generated by Django 5.0.6 on 2025-11-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_estimate_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estimateparty'),
        ),
    ]
