# Generated by Django 5.0.6 on 2025-10-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_vehiclememo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleregistration',
            old_name='registation_area',
            new_name='registration_area',
        ),
        migrations.RenameField(
            model_name='vehicleregistration',
            old_name='registation_no',
            new_name='registration_no',
        ),
    ]
