# Generated by Django 5.0.6 on 2025-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_estimate_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='表示名'),
        ),
    ]
