# Generated by Django 5.0.6 on 2025-10-17 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', '未対応'), ('done', '対応済み')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('receiver_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_business_communications', to='core.shop')),
                ('sender_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_business_communications', to='core.shop')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('kana', models.CharField(blank=True, max_length=100, verbose_name='フリガナ')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='携帯電話番号')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='会社名')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='会社電話番号')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customerclass')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gender')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
                ('source_customer', models.ForeignKey(blank=True, help_text='元となった顧客（任意）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_parties', to='core.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '見積用顧客スナップショット',
                'verbose_name_plural': '見積用顧客スナップショット',
                'db_table': 'estimate_parties',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_no', models.BigIntegerField(unique=True, verbose_name='見積番号')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('issued', '提出済み'), ('expired', '期限切れ'), ('ordered', '受注済み')], default='draft', max_length=20, verbose_name='ステータス')),
                ('estimate_date', models.DateField(blank=True, null=True, verbose_name='見積日')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小計')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='値引額')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税額')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimates', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='core.shop')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='core.estimateparty')),
            ],
            options={
                'verbose_name': '見積',
                'verbose_name_plural': '見積',
                'db_table': 'estimates',
                'ordering': ['-created_at'],
            },
        ),
    ]
