# Generated by Django 5.0.6 on 2025-11-26 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.customerclass'),
        ),
    ]
