# Generated by Django 5.0.6 on 2025-11-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customer_customer_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trade_in', models.BooleanField(default=False, help_text='Trueなら下取り車両、Falseなら商談車両')),
                ('vehicle_name', models.CharField(blank=True, max_length=100)),
                ('displacement', models.IntegerField(blank=True, null=True)),
                ('model_year', models.CharField(blank=True, max_length=10)),
                ('new_car_type', models.CharField(blank=True, max_length=20)),
                ('color_name', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('model_code', models.CharField(blank=True, max_length=50)),
                ('chassis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_vehicles', to='core.order')),
            ],
            options={
                'db_table': 'order_vehicles',
            },
        ),
    ]
