# Generated by Django 5.0.6 on 2025-12-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivered_at',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='memo',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='sales_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.delivery')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_management', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(max_length=20)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.paymentmanagement')),
            ],
        ),
    ]
