# Generated by Django 5.0.6 on 2025-12-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_delivered_at_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sales_date',
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField()),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_type', models.CharField(choices=[('auto', '自動計上'), ('manual', '手動計上')], default='manual', max_length=20)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.order')),
            ],
        ),
    ]
