# Generated by Django 5.0.6 on 2025-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_order_sales_date_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
