# Generated by Django 5.0.6 on 2025-12-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_orderitem_delivery_date_orderitem_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('not_delivered', '未納品'), ('partial', '一部納品'), ('delivered', '納品済')], default='not_delivered', max_length=20),
        ),
    ]
