# Generated by Django 5.0.6 on 2025-12-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
