# Generated by Django 5.0.6 on 2025-12-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_final_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
