# Generated by Django 5.0.6 on 2025-12-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
