# Generated by Django 5.0.6 on 2025-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_order_final_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
