# Generated by Django 5.0.6 on 2025-12-24 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_schedule_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscommunication',
            name='staff',
        ),
        migrations.AddField(
            model_name='businesscommunication',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_business_communications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
