# Generated by Django 5.0.6 on 2026-01-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_businesscommunication_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCommunicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='business_communications/')),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.businesscommunication')),
            ],
            options={
                'db_table': 'business_communication_attachments',
            },
        ),
    ]
