# Generated by Django 5.0.6 on 2026-01-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_product_small_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='分析用カテゴリ（車両・メーカー・新車/中古など）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='core.category'),
        ),
    ]
