# Generated by Django 5.0.6 on 2026-01-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_estimateitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='分析用カテゴリ（見積から引き継ぎ）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.category'),
        ),
    ]
