# Generated by Django 5.0.6 on 2026-01-30 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_orderitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('new', '新車'), ('used', '中古車'), ('rental_up', 'レンタルアップ'), ('consignment', '委託販売')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('new', '新車'), ('used', '中古車'), ('rental_up', 'レンタルアップ'), ('consignment', '委託販売')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='実作業担当スタッフ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
