# Generated by Django 5.0.6 on 2026-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_estimateitem_sale_type_orderitem_sale_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_search',
            field=models.CharField(db_index=True, default='', editable=False, max_length=300, verbose_name='検索用商品名'),
            preserve_default=False,
        ),
    ]
