# Generated by Django 5.0.6 on 2026-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_product_name_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='item_type',
            field=models.CharField(choices=[('vehicle', '車両'), ('accessory', '用品'), ('insurance', '保険'), ('fee', '諸費用')], db_index=True, default='accessory', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('vehicle', '車両'), ('accessory', '用品'), ('insurance', '保険'), ('fee', '諸費用')], db_index=True, default='accessory', max_length=20),
        ),
    ]
