# Generated by Django 5.0.6 on 2026-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_estimateitem_item_type_orderitem_item_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customervehicle',
            name='uq_customer_vehicle_from',
        ),
        migrations.RemoveIndex(
            model_name='customervehicle',
            name='customer_ve_custome_bcbf35_idx',
        ),
        migrations.RemoveIndex(
            model_name='customervehicle',
            name='customer_ve_vehicle_b0903c_idx',
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='customervehicle',
            index=models.Index(fields=['customer', 'is_current'], name='customer_ve_custome_8d3e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='customervehicle',
            index=models.Index(fields=['vehicle', 'is_current'], name='customer_ve_vehicle_c4e92f_idx'),
        ),
        migrations.AddIndex(
            model_name='customervehicle',
            index=models.Index(fields=['owned_from'], name='customer_ve_owned_f_b4cd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='customervehicle',
            index=models.Index(fields=['owned_to'], name='customer_ve_owned_t_f1f2aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='customervehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('vehicle',), name='uq_vehicle_current_owner'),
        ),
    ]
