# Generated by Django 5.0.6 on 2026-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_customervehicle_uq_customer_vehicle_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='code',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='core.category'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='メーカー名'),
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturers',
        ),
    ]
