# Generated by Django 5.0.6 on 2026-02-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_manufacturer_options_remove_manufacturer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('vehicle', '車両'), ('item', '商品'), ('expense', '諸費用'), ('insurance', '保険'), ('other', 'その他')], help_text='最上位カテゴリのみ設定', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
        migrations.CreateModel(
            name='CategoryManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_links', to='core.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='core.manufacturer')),
            ],
            options={
                'db_table': 'category_manufacturers',
                'indexes': [models.Index(fields=['category'], name='category_ma_categor_4f3fd5_idx'), models.Index(fields=['manufacturer'], name='category_ma_manufac_7bd8a5_idx')],
                'unique_together': {('category', 'manufacturer')},
            },
        ),
    ]
