# Generated by Django 5.0.6 on 2026-02-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_manufacturer_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='メーカーグループ名')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='グループコード')),
            ],
            options={
                'db_table': 'manufacturer_groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='manufacturer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.manufacturergroup'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='core.manufacturergroup'),
        ),
        migrations.DeleteModel(
            name='CategoryManufacturer',
        ),
    ]
