# Generated by Django 5.0.6 on 2026-02-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatevehicle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_vehicles', to='core.category'),
        ),
        migrations.AddField(
            model_name='estimatevehicle',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
