# Generated by Django 5.0.6 on 2026-02-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_estimatevehicle_category_estimatevehicle_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatevehicle',
            name='unit_price',
        ),
    ]
