# Generated by Django 5.0.6 on 2026-02-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_estimatevehicle_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatevehicle',
            name='source_customer_vehicle',
            field=models.ForeignKey(blank=True, help_text='既存所有車両から生成された場合', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customervehicle'),
        ),
    ]
