# Generated by Django 5.0.6 on 2026-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_estimatevehicle_source_customer_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='vehicle_mode',
            field=models.CharField(choices=[('sale', '車両販売'), ('maintenance', '既存車両メンテナンス'), ('none', '車両なし')], default='none', max_length=20),
        ),
    ]
