# Generated by Django 5.0.6 on 2026-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_estimate_vehicle_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vehicle_mode',
            field=models.CharField(choices=[('sale', '車両販売'), ('maintenance', '既存車両メンテナンス'), ('none', '車両なし')], default='none', max_length=20),
        ),
    ]
