# Generated by Django 5.0.6 on 2026-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_vehicle_color_code_alter_vehicle_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatevehicle',
            name='color_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimatevehicle',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estimatevehicle',
            name='engine_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estimatevehicle',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
