# Generated by Django 5.0.6 on 2026-03-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_estimatevehicle_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工賃'),
        ),
    ]
