# Generated by Django 5.0.6 on 2026-03-12 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_estimateitem_labor_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscommunication',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='businesscommunication',
            name='title',
        ),
        migrations.AddField(
            model_name='businesscommunication',
            name='receiver_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_staff_business_communications', to=settings.AUTH_USER_MODEL, verbose_name='送信先スタッフ'),
        ),
        migrations.AddField(
            model_name='businesscommunication',
            name='sender_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_staff_business_communications', to=settings.AUTH_USER_MODEL, verbose_name='送信元スタッフ'),
        ),
        migrations.AddField(
            model_name='businesscommunication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='businesscommunication',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='businesscommunication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='businesscommunication',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_business_communications', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='businesscommunication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_communications', to='core.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='businesscommunication',
            name='receiver_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_business_communications', to='core.shop', verbose_name='送信先店舗'),
        ),
        migrations.AlterField(
            model_name='businesscommunication',
            name='sender_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_business_communications', to='core.shop', verbose_name='送信元店舗'),
        ),
        migrations.AlterField(
            model_name='businesscommunication',
            name='status',
            field=models.CharField(choices=[('pending', '未対応'), ('done', '対応済み')], default='pending', max_length=20, verbose_name='対応状況'),
        ),
        migrations.AlterField(
            model_name='businesscommunicationattachment',
            name='bytes',
            field=models.PositiveIntegerField(default=0, verbose_name='ファイルサイズ'),
        ),
        migrations.AlterField(
            model_name='businesscommunicationattachment',
            name='communication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.businesscommunication', verbose_name='業務連絡'),
        ),
        migrations.AlterField(
            model_name='businesscommunicationattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='businesscommunicationattachment',
            name='file',
            field=models.ImageField(upload_to='business_communications/', verbose_name='ファイル'),
        ),
        migrations.AlterField(
            model_name='businesscommunicationattachment',
            name='mime',
            field=models.CharField(blank=True, max_length=100, verbose_name='MIMEタイプ'),
        ),
        migrations.AlterModelTable(
            name='businesscommunication',
            table='business_communications',
        ),
        migrations.CreateModel(
            name='BusinessCommunicationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='スレッドタイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_communication_threads', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_threads', to='core.customer', verbose_name='顧客')),
            ],
            options={
                'db_table': 'business_communication_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='businesscommunication',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.businesscommunicationthread', verbose_name='スレッド'),
        ),
    ]
