# Generated by Django 5.0.6 on 2026-03-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_businesscommunication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatevehicle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color'),
        ),
    ]
