# Generated by Django 5.0.6 on 2026-03-17 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_ordervehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervehicle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_vehicles', to='core.category'),
        ),
    ]
