# Generated by Django 5.0.6 on 2026-03-18 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_estimateitem_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervehicle',
            name='source_customer_vehicle',
            field=models.ForeignKey(blank=True, help_text='元となる顧客所有車両', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customervehicle'),
        ),
    ]
