# Generated by Django 5.0.6 on 2026-03-25 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_ordervehicle_source_customer_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorymiddle',
            name='large',
        ),
        migrations.RemoveField(
            model_name='productcategorysmall',
            name='middle',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manufacturer'),
        ),
        migrations.DeleteModel(
            name='ProductCategoryLarge',
        ),
        migrations.DeleteModel(
            name='ProductCategoryMiddle',
        ),
        migrations.DeleteModel(
            name='ProductCategorySmall',
        ),
    ]
