# Generated by Django 5.0.6 on 2026-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_productcategorymiddle_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
