# Generated by Django 5.0.6 on 2026-03-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_orderitem_labor_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='item_type',
            field=models.CharField(choices=[('vehicle', '車両'), ('accessory', '用品'), ('insurance', '保険'), ('fee', '諸費用'), ('discount', '値引き')], db_index=True, default='accessory', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('vehicle', '車両'), ('accessory', '用品'), ('insurance', '保険'), ('fee', '諸費用'), ('discount', '値引き')], db_index=True, default='accessory', max_length=20),
        ),
    ]
