# Generated by Django 5.0.6 on 2026-03-30 15:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_estimateitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='final_adjustment',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='final_adjustment',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
    ]
