# Generated by Django 5.0.6 on 2026-03-31 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_estimate_final_adjustment_order_final_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estimate'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('delivery', '納車'), ('free', 'フリー')], default='free', max_length=20),
        ),
    ]
