# Generated by Django 5.0.6 on 2026-03-31 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_schedule_delivery_location_schedule_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='delivery_location',
        ),
        migrations.AddField(
            model_name='schedule',
            name='delivery_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='core.shop'),
        ),
    ]
