# Generated by Django 5.0.6 on 2026-04-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_schedule_delivery_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.estimate'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.order'),
        ),
    ]
