# Generated by Django 5.0.6 on 2026-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_schedule_customer_alter_schedule_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
