# Generated by Django 5.0.6 on 2026-04-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_schedule_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateVehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_area', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('certification_no', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_expiration', models.DateField(blank=True, null=True)),
                ('first_registration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.estimatevehicle')),
            ],
            options={
                'db_table': 'estimate_vehicle_registrations',
            },
        ),
        migrations.CreateModel(
            name='OrderVehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_area', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('certification_no', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_expiration', models.DateField(blank=True, null=True)),
                ('first_registration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.ordervehicle')),
            ],
            options={
                'db_table': 'order_vehicle_registrations',
            },
        ),
    ]
