# Generated by Django 5.0.6 on 2026-04-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_estimatevehicleregistration_ordervehicleregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.CharField(choices=[('trade_in', '下取車'), ('cash', '現金'), ('card', 'カード・クーポン'), ('credit', 'クレジット'), ('advance', '前受金')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.order')),
            ],
        ),
    ]
