# Generated by Django 5.0.6 on 2026-04-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_unit_estimate_unit_orderitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='unit',
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='core.unit'),
        ),
    ]
