# Generated by Django 5.0.6 on 2026-04-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_estimate_unit_estimateitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('bodily_injury', models.CharField(blank=True, max_length=50)),
                ('property_damage', models.CharField(blank=True, max_length=50)),
                ('passenger', models.CharField(blank=True, max_length=50)),
                ('vehicle', models.CharField(blank=True, max_length=50)),
                ('option', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='core.estimate')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='core.order')),
            ],
        ),
    ]
