# Generated by Django 5.0.6 on 2026-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
