# Generated by Django 5.0.6 on 2026-04-15 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_estimate_memo_order_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscommunication',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_communications', to='core.customer', verbose_name='顧客'),
        ),
    ]
