# Generated by Django 5.0.6 on 2026-04-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_businesscommunication_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('taxable', '課税'), ('non_taxable', '非課税')], help_text='主に費用カテゴリで使用', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businesscommunicationthread',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='core.customer', verbose_name='顧客'),
        ),
    ]
