# Generated by Django 5.0.6 on 2026-04-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_category_tax_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('vehicle', '車両'), ('item', '商品'), ('expense', '費用'), ('insurance', '保険'), ('other', 'その他')], help_text='最上位カテゴリのみ設定', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('taxable', '課税'), ('non_taxable', '非課税')], db_index=True, max_length=20, null=True),
        ),
    ]
