# Generated by Django 5.0.6 on 2026-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_category_category_type_alter_category_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
