# Generated by Django 5.0.6 on 2026-04-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_estimate_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatevehicle',
            name='new_car_type',
        ),
        migrations.RemoveField(
            model_name='ordervehicle',
            name='new_car_type',
        ),
        migrations.AddField(
            model_name='estimatevehicle',
            name='sale_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordervehicle',
            name='sale_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='sale_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
