# Generated by Django 5.0.6 on 2026-04-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_estimatevehicle_new_car_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='internal_memo',
            field=models.TextField(blank=True, default='', verbose_name='内部メモ'),
        ),
    ]
