# Generated by Django 5.0.6 on 2026-04-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_estimate_internal_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_memo',
            field=models.TextField(blank=True, default='', verbose_name='内部メモ'),
        ),
    ]
