# Generated by Django 5.0.6 on 2026-05-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_businesscommunicationthread_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('ordered', '受注確定'), ('cancelled', 'キャンセル'), ('delivered', '納車済')], default='draft', max_length=20),
        ),
    ]
