# Generated by Django 5.0.6 on 2026-05-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_settlement_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('ordered', '受注確定'), ('cancelled', 'キャンセル'), ('delivered', '納車済'), ('sales_completed', '売上計上済')], default='draft', max_length=20),
        ),
    ]
