# Generated by Django 5.0.6 on 2026-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('executive', '役員'), ('accounting', '経理総務'), ('manager', 'MGR・SV'), ('store_manager', '店長'), ('staff', 'スタッフ'), ('admin', '管理者(旧)')], default='staff', max_length=20),
        ),
    ]
