# Generated by Django 5.0.6 on 2026-06-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
