# Generated by Django 5.0.6 on 2026-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_add_postal_code_registration_number_to_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='適格請求書登録番号')),
            ],
            options={
                'verbose_name': '会社設定',
            },
        ),
        migrations.RemoveField(
            model_name='shop',
            name='registration_number',
        ),
    ]
