# Generated by Django 5.0.6 on 2026-06-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_add_closing_day_to_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
                ('payment_type', models.CharField(choices=[('loan', 'ローン'), ('card', 'カード'), ('qr', 'QR決済')], max_length=20, verbose_name='支払種別')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'db_table': 'payment_companies',
                'ordering': ['payment_type', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='settlement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='core.paymentcompany'),
        ),
    ]
