# Generated by Django 5.0.6 on 2026-06-10 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_add_cancel_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_vehicles', to='core.order'),
        ),
    ]
