# Generated by Django 5.0.6 on 2026-06-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_add_source_order_to_customer_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='書類名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('paper_width', models.FloatField(default=210, verbose_name='用紙幅 (mm)')),
                ('paper_height', models.FloatField(default=297, verbose_name='用紙高さ (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='type',
            field=models.CharField(blank=True, choices=[('mandatory', '自賠責'), ('optional', '任意保険')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='項目名（管理用）')),
                ('source_key', models.CharField(choices=[('customer.name', '顧客氏名'), ('customer.kana', '顧客フリガナ'), ('customer.postal_code', '郵便番号'), ('customer.address', '住所'), ('customer.phone', '電話番号'), ('customer.mobile_phone', '携帯電話'), ('vehicle.vehicle_name', '車名'), ('vehicle.model_code', '型式'), ('vehicle.chassis_no', '車台番号'), ('vehicle.engine_type', '原動機型式'), ('vehicle.displacement', '排気量'), ('vehicle.model_year', '年式'), ('vehicle.color_name', '車体の色'), ('registration.registration_no', '標識番号'), ('registration.registration_area', '登録地域'), ('registration.inspection_expiration', '車検満了日'), ('registration.first_registration_date', '初年度登録'), ('company.name', '会社名'), ('company.address', '会社住所'), ('company.phone', '会社電話'), ('date_today', '今日の日付 (YYYY/MM/DD)'), ('date_wareki', '今日の日付（和暦）'), ('static', '固定テキスト'), ('input', '手入力')], max_length=60, verbose_name='値の取得元')),
                ('static_value', models.CharField(blank=True, help_text="source_key='static' のときに使用", max_length=200, verbose_name='固定テキスト')),
                ('input_label', models.CharField(blank=True, help_text="source_key='input' のときに印刷画面で表示するラベル", max_length=100, verbose_name='手入力ラベル')),
                ('x', models.FloatField(default=0, verbose_name='X座標 (mm)')),
                ('y', models.FloatField(default=0, verbose_name='Y座標 (mm)')),
                ('font_size', models.FloatField(default=10, verbose_name='フォントサイズ (pt)')),
                ('letter_spacing', models.FloatField(default=0, help_text='1文字1マスの欄に入力するときに使用', verbose_name='文字間隔 (mm)')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.documenttemplate')),
            ],
            options={
                'db_table': 'document_fields',
                'ordering': ['order', 'id'],
            },
        ),
    ]
